nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-sources.js

packageExtensions:
  electron-webpack@*:
    dependencies:
      '@babel/preset-env': '*'
      '@babel/core': '*'
      '@babel/plugin-syntax-dynamic-import': '*'
