[package]
name = "starbound-assets"
version = "0.1.0"
authors = ["Adam Madsen <madsen.adam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
nom = "5.1.1"
serde_json = { version = "1.0.53", features = ["preserve_order"] }
either = "1.5.3"
serde = { version = "1.0.110", features = ["derive"] }
memmap = "0.7.0"
progress_bar = "0.1.3"
clap = { version = "2.33.1", features = ["color"] }
